In [2]:
import pandas as pd

In [4]:
data = {
    "Restaurant": ["R1", "R2", "R2"],
    "Votes": [120,500,200],
    "Location": ["South","North","East"]
}

In [9]:
restaurant_df = pd.DataFrame(data)
restaurant_df

  Restaurant  Votes Location
0         R1    120    South
1         R2    500    North
2         R2    200     East

In [10]:
restaurant_df.shape

(3, 3)

In [11]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv .

--2025-02-10 20:46:36--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 99.86.17.86, 99.86.17.139, 99.86.17.111, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|99.86.17.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M  52.8MB/s    in 1.3s

2025-02-10 20:46:37 (52.8 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: zomato_dataset.csv and ./zomato_dataset.csv are identical

In [43]:
df = pd.read_csv('zomato_dataset.csv')

In [44]:
df.head(6)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,'600.0',"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

In [15]:
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [16]:
df['rate'].str.split("/")

0         [4.1, 5]
1         [4.1, 5]
2         [3.8, 5]
3         [3.7, 5]
4         [3.8, 5]
           ...
23188    [3.8 , 5]
23189    [3.9 , 5]
23190    [2.8 , 5]
23191    [2.5 , 5]
23192    [4.3 , 5]
Name: rate, Length: 23193, dtype: object

In [17]:
df['rate'].str.split("/",n=1)

0         [4.1, 5]
1         [4.1, 5]
2         [3.8, 5]
3         [3.7, 5]
4         [3.8, 5]
           ...
23188    [3.8 , 5]
23189    [3.9 , 5]
23190    [2.8 , 5]
23191    [2.5 , 5]
23192    [4.3 , 5]
Name: rate, Length: 23193, dtype: object

In [27]:
df["only_rating"] = [i[:-2] for i in (df.rate)]
df['only_rating']

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23193, dtype: object

In [28]:
df['rate'].str[:-2]

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23193, dtype: object

In [25]:
df["is_good"] = df["votes"] > 500
df["is_good"]

0         True
1         True
2         True
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192    False
Name: is_good, Length: 23193, dtype: bool

In [45]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [48]:
df.drop("menu_item", axis = 1)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",Pubs and bars,Whitefield

In [52]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [50]:
df.column()

AttributeError: 'DataFrame' object has no attribute 'column'

In [38]:
df.drop("ratings", axis =1, inplace=True)

KeyError: "['ratings'] not found in axis"

In [54]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel | None' = None, *, axis: 'Axis' = 0, index: 'IndexLabel | None' = None, columns: 'IndexLabel | None' = None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [55]:
df["cuisines"].unique()

array(['North Indian, Mughlai, Chinese', 'Chinese, North Indian, Thai',
       'Cafe, Mexican, Italian', ..., 'Andhra, Hyderabadi, Biryani',
       'Andhra, North Indian, South Indian', 'Thai, Chinese, Momos'],
      dtype=object)

In [56]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [66]:
ratings_count = df["only_rating"].value_counts(ascending=False)
ratings_count

only_rating
3.9     1689
3.9     1549
4.0     1469
4.1     1398
4.0     1391
        ...
2.2        7
2.0        7
2.0        4
1.8        3
1.8        2
Name: count, Length: 63, dtype: int64

In [61]:
df["only_rating"] = [i[:-2] for i in (df.rate)]
df["only_rating"]

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: object

In [63]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)', 'only_rating'],
      dtype='object')

In [68]:
df["listed_in(type)"].value_counts()

listed_in(type)
Delivery              10625
Dine-out               8009
Desserts               1333
Cafes                  1047
Drinks & nightlife      890
Buffet                  762
Pubs and bars           527
Name: count, dtype: int64

In [69]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),only_rating
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8

In [70]:
df.index

RangeIndex(start=0, stop=23193, step=1)

In [76]:
# Implicit Index look at the 1st column
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),only_rating
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8

In [77]:
# Explicit Index 
df_explicit = df.set_index("name")
df_explicit.head()

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),only_rating
name,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8

In [78]:
df_explicit.index

Index(['Jalsa', 'Spice Elephant', 'San Churro Cafe', 'Addhuri Udupi Bhojana',
       'Grand Village', 'Timepass Dinner', 'Onesta', 'Penthouse Cafe',
       'Smacznego', 'CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley',
       ...
       'BAR BAR', 'The Beer Cafe', 'Pablo's Gastrobar', 'Oliver's Pub & Diner',
       'Smaaash', 'Izakaya Gastro Pub',
       'M Bar - Bengaluru Marriott Hotel Whitefield', 'Keys Cafe - Keys Hotel',
       'Bhagini', 'Chime - Sheraton Grand Bengaluru Whitefield Hotel &...'],
      dtype='object', name='name', length=23193)

In [81]:
# Reading implicit dataset 
df.iloc[0]

url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
name                                                                       Jalsa
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
only_rating                                                                  4.1
Name: 0, dtype: object

In [84]:
df_explicit.iloc[0]

url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
only_rating                                                                  4.1
Name: Jalsa, dtype: object

In [ ]:
df.reset_index(True)

In [85]:
data.loc["Jalsa"]

AttributeError: 'dict' object has no attribute 'loc'

In [86]:
df.iloc[0:2,0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [88]:
df.iloc[-2:, -1]

23191    2.5
23192    4.3
Name: only_rating, dtype: object

In [89]:
data = {
    "Restaurant": ["R1", "R2", "R2"],
    "Votes": [120,500,200],
    "Location": ["South","North","East"]
}

# Day 5 : Pandas Classes 

- duplicates

        df_no_duplicates_subset = sample_df.drop_duplicate(subset=["Votes],keep="first)

- sorting 

        sample_df.sort_valies(by=["Votes", "Rating"], ascending=[False,True]

- merge two datasets ( pd.concat , pd.merge)

- .apply(uppercase_title)
- .apply(lamda x: x.upper())
- lamda functions 

    df.groupby('category)['rating'].mean()
    df.groupby('category)['rating'].mean().loc[lambda x:x >=4]

- axis in pandas
- functions in pandas
- df.isnull().sum()
- grouping i.e df.groupby

        df.groupby('user_name')['product_name'].count()
        df.groupby('category)['rating'].mean()
        df.groupby('category)['rating'].mean().loc[lambda x:x >=4]
        df.groupby('user_id').filter(lambda x:x)

- df.isna().sum # missing records
- df.dropna()
- String Functions
        - df['about_product].str.contains('Compaitability',case = False)

In [1]:
import pandas as pd

# Sample DataFrames
samples_orders = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003'],
    'user_id': ['U001', 'U002', 'U003'],
    'review_id': ['R001', 'R002', 'R003']
})

samples_products = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P004'],
    'product_name': ['Product A', 'Product B', 'Product D'],
    'category': ['Category 1', 'Category 2', 'Category 3']
})